openapi: 3.0.0
info:
  title: Users API
  version: 1.0.0
  description: API para gestión de usuarios.

paths:
  /api/users:
    get:
      summary: Listar todos los usuarios
      responses:
        '200':
          description: Lista de usuarios
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
    post:
      summary: Crear un nuevo usuario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserInput'
      responses:
        '201':
          description: Usuario creado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

  /api/users/{id}:
    get:
      summary: Obtener usuario por ID
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: ID del usuario
      responses:
        '200':
          description: Usuario encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: Usuario no encontrado
    put:
      summary: Actualizar usuario por ID
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: ID del usuario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserInput'
      responses:
        '200':
          description: Usuario actualizado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: Usuario no encontrado
    delete:
      summary: Eliminar usuario por ID
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: ID del usuario
      responses:
        '204':
          description: Usuario eliminado
        '404':
          description: Usuario no encontrado

components:
  schemas:
    User:
      type: object
      properties:
        _id:
          type: string
          description: Identificador único
        first_name:
          type: string
          description: Nombre
        last_name:
          type: string
          description: Apellido
        email:
          type: string
          format: email
          description: Correo electrónico
        age:
          type: integer
          description: Edad
        role:
          type: string
          description: Rol del usuario
      required:
        - _id
        - first_name
        - last_name
        - email
    UserInput:
      type: object
      properties:
        first_name:
          type: string
          description: Nombre
        last_name:
          type: string
          description: Apellido
        email:
          type: string
          format: email
          description: Correo electrónico
        age:
          type: integer
          description: Edad
        role:
          type: string
          description: Rol del usuario
      required:
        - first_name
        - last_name
        - email
